/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Service.GiaoVienService;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import object.GiaoVien;

/**
 *
 * @author HL94NVT
 */
public class Quanlygiaovien extends javax.swing.JFrame {
    GiaoVienService giaoVienService;
    GiaoVien giaoVien;
    DefaultTableModel defaultTableModel;
    /**
    
     */
    public Quanlygiaovien() {
        initComponents();
        
        giaoVien=new GiaoVien();
        giaoVienService=new GiaoVienService();
        defaultTableModel=new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
                return  false; //To change body of generated methods, choose Tools | Templates.
            }
            
        };
        GiaoVienTable.setModel(defaultTableModel);
        defaultTableModel.addColumn("magiaovien");
        defaultTableModel.addColumn("tengiaovien");
        defaultTableModel.addColumn("hocvi");
        //defaultTableModel.addColumn("ngaycong");
        List<GiaoVien> giaoviens= giaoVienService.getAllGiaoVien();
        for(GiaoVien giaovien:giaoviens){
            defaultTableModel.addRow(new Object[]{giaovien.getMaGiaoVien(),giaovien.getTenGiaoVien(),
                giaovien.getHocVi()});
        }
        setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        GiaoVienTable = new javax.swing.JTable();
        btnThoat = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMaGiaoVien = new javax.swing.JTextField();
        txtTenGiaoVien = new javax.swing.JTextField();
        txtHocVi = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JButton();
        btnTim = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quản lý giáo viên");

        GiaoVienTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        GiaoVienTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã giáo viên", "Tên giáo viên", "Học vị"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        GiaoVienTable.setRowHeight(20);
        GiaoVienTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        GiaoVienTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GiaoVienTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(GiaoVienTable);

        btnThoat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Mã giáo viên");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Tên giáo viên");

        btnThem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Học vị");

        btnRefresh.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnTim.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnTim.setText("Tìm kiếm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(552, 552, 552)
                                .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(227, 227, 227)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTenGiaoVien)
                                    .addComponent(txtMaGiaoVien)
                                    .addComponent(txtHocVi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnTim, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                    .addComponent(btnSua, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnThem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                    .addComponent(btnXoa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(91, 91, 91)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5))))))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMaGiaoVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTenGiaoVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHocVi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnTim)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        giaoVien.setMaGiaoVien(txtMaGiaoVien.getText());
        giaoVien.setTenGiaoVien(txtTenGiaoVien.getText());
        giaoVien.setHocVi(txtHocVi.getText());
        //giaoVien.setNgayCong(Integer.parseInt(txtNgayCong.getText()));
        giaoVienService.addGiaoVien(giaoVien);
        defaultTableModel.setRowCount(0);
        List<GiaoVien> giaoviens= giaoVienService.getAllGiaoVien();
        for(GiaoVien giaovien:giaoviens){
            defaultTableModel.addRow(new Object[]{giaovien.getMaGiaoVien(),giaovien.getTenGiaoVien(),
                giaovien.getHocVi()});
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        defaultTableModel.setRowCount(0);
        List<GiaoVien> giaoviens= giaoVienService.getAllGiaoVien();
        for(GiaoVien giaovien:giaoviens){
            defaultTableModel.addRow(new Object[]{giaovien.getMaGiaoVien(),giaovien.getTenGiaoVien(),
                giaovien.getHocVi()});
        }
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int row = GiaoVienTable.getSelectedRow();
        if(row==-1){
            JOptionPane.showMessageDialog(Quanlygiaovien.this, "Vui lòng chọn user trước","Lỗi", JOptionPane.ERROR_MESSAGE);
            
        }else{
            int confirm=JOptionPane.showConfirmDialog(Quanlygiaovien.this, "Bạn muốn chắc chắn xóa không?");
            if(confirm==JOptionPane.YES_OPTION){
                String magiaovien= (String) GiaoVienTable.getValueAt(row, 0);
                giaoVienService.deleteGiaoVien(magiaovien);
                List<GiaoVien> giaoviens= giaoVienService.getAllGiaoVien();
                for(GiaoVien giaovien:giaoviens){
                    defaultTableModel.addRow(new Object[]{giaovien.getMaGiaoVien(),giaovien.getTenGiaoVien(),
                    giaovien.getHocVi()});
                }
            }
        }
        btnRefreshActionPerformed(evt);
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        giaoVien.setMaGiaoVien(txtMaGiaoVien.getText());
        giaoVien.setTenGiaoVien(txtTenGiaoVien.getText());
        giaoVien.setHocVi(txtHocVi.getText());
        //giaoVien.setNgayCong(Integer.parseInt(txtNgayCong.getText()));
        giaoVienService.updateGiaoVien(giaoVien);
        
        defaultTableModel.setRowCount(0);
        List<GiaoVien> giaoviens= giaoVienService.getAllGiaoVien();
        for(GiaoVien giaovien:giaoviens){
            defaultTableModel.addRow(new Object[]{giaovien.getMaGiaoVien(),giaovien.getTenGiaoVien(),
                giaovien.getHocVi(),giaovien.getNgayCong()});
        }
    }//GEN-LAST:event_btnSuaActionPerformed
/**/
    private void GiaoVienTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GiaoVienTableMouseClicked
        // TODO add your handling code here:
        int row=GiaoVienTable.getSelectedRow();
        txtMaGiaoVien.setText((String) GiaoVienTable.getValueAt(row, 0));
        txtTenGiaoVien.setText((String) GiaoVienTable.getValueAt(row, 1));
        txtHocVi.setText((String) GiaoVienTable.getValueAt(row, 2));
        //txtNgayCong.setText(String.valueOf(GiaoVienTable.getValueAt(row, 3))  );
    }//GEN-LAST:event_GiaoVienTableMouseClicked

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:
        List<GiaoVien> li=giaoVienService.find(txtMaGiaoVien.getText(),txtTenGiaoVien.getText(),txtHocVi.getText());
        defaultTableModel.setRowCount(0);
        List<GiaoVien> giaoviens= li;
                for(GiaoVien giaovien:giaoviens){
                    defaultTableModel.addRow(new Object[]{giaovien.getMaGiaoVien(),giaovien.getTenGiaoVien(),
                    giaovien.getHocVi()});
                }
    }//GEN-LAST:event_btnTimActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        new trangchu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnThoatActionPerformed
    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable GiaoVienTable;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtHocVi;
    private javax.swing.JTextField txtMaGiaoVien;
    private javax.swing.JTextField txtTenGiaoVien;
    // End of variables declaration//GEN-END:variables
}
