/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import Service.GiaoVienService;
import Service.LichTrucService;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import object.GiaoVien;
import object.LichTruc;

/**
 *
 * @author HL94NVT
 */
public class QuanLyLichTrucVaTinhCong extends javax.swing.JFrame {

    /**
     * Creates new form QuanLyLichTrucVaTinhCong
     */
    SimpleDateFormat dateFormat=new SimpleDateFormat("yyyy-MM-dd");
    LichTrucService lichTrucService;
    DefaultTableModel defaultTableModel;
    public QuanLyLichTrucVaTinhCong() {
        initComponents();
        lichTrucService = new LichTrucService();
        defaultTableModel = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; //không cho phép thay đổi dữ liệu của bảng
            }

        };
        jTable1.setModel(defaultTableModel);
        defaultTableModel.setColumnIdentifiers(new Object[]{"Mã giáo viên", "Tên giáo viên", "Ngày trực", "Ghi chú"});

        hienThi(lichTrucService.getAll());

        //set cac item cho combobox
        for (GiaoVien i : (new GiaoVienService()).getAllGiaoVien()) {
            String maGV = i.getMaGiaoVien();
            boolean ktra = false;
            for (int j = 0; j < cbbMaGV.getItemCount(); j++) {
                if (maGV.equalsIgnoreCase(cbbMaGV.getItemAt(j))) {
                    ktra = true;
                    break;
                }
            }
            if (!ktra) {
                cbbMaGV.addItem(maGV);
                cbbTenGV.addItem(i.getTenGiaoVien());

                cbbMaGVCu.addItem(maGV);
                cbbTenGVCu.addItem(i.getTenGiaoVien());

                cbbMaGVMoi.addItem(maGV);
                cbbTenGVMoi.addItem(i.getTenGiaoVien());

            }

        }
        //them item trắng để thuận tiện cho việc tìm kiếm
        cbbMaGV.addItem("");
        cbbMaGV.setSelectedItem("");
        cbbTenGV.addItem("");
        cbbTenGV.setSelectedItem("");

        cbbMaGVCu.addItem("");
        cbbMaGVCu.setSelectedItem("");
        cbbTenGVCu.addItem("");
        cbbTenGVCu.setSelectedItem("");

        cbbMaGVMoi.addItem("");
        cbbMaGVMoi.setSelectedItem("");
        cbbTenGVMoi.addItem("");
        cbbTenGVMoi.setSelectedItem("");

        //ràng các item của các combobox với nhau
        cbbMaGV.addActionListener((e) -> {
            cbbTenGV.setSelectedIndex(cbbMaGV.getSelectedIndex());
        });
        cbbTenGV.addActionListener((e) -> {
            cbbMaGV.setSelectedIndex(cbbTenGV.getSelectedIndex());
        });

        cbbMaGVCu.addActionListener((e) -> {
            cbbTenGVCu.setSelectedIndex(cbbMaGVCu.getSelectedIndex());
        });
        cbbTenGVCu.addActionListener((e) -> {
            cbbMaGVCu.setSelectedIndex(cbbTenGVCu.getSelectedIndex());
        });

        cbbMaGVMoi.addActionListener((e) -> {
            cbbTenGVMoi.setSelectedIndex(cbbMaGVMoi.getSelectedIndex());
        });
        cbbTenGVMoi.addActionListener((e) -> {
            cbbMaGVMoi.setSelectedIndex(cbbTenGVMoi.getSelectedIndex());
        });
        
        //cho frame chỉnh sửa ra giữ màn hình
        setLocationRelativeTo(null);
    }
    public void hienThi(List<LichTruc> listLichTruc) {
        defaultTableModel.setRowCount(0);

        for (LichTruc i : listLichTruc) {
            defaultTableModel.addRow(new Object[]{i.getGiaoVien().getMaGiaoVien(), i.getGiaoVien().getTenGiaoVien(), i.getNgayTruc(), i.getGhiChu()});
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel7 = new javax.swing.JPanel();
        cbbMaGVMoi = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cbbTenGVMoi = new javax.swing.JComboBox<>();
        txtNgayTrucMoi = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtAreaGhiChuMoi = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        btnChinhSua = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        cbbMaGVCu = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cbbTenGVCu = new javax.swing.JComboBox<>();
        txtNgayTrucCu = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAreaGhiChuCu = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        jFrame2 = new javax.swing.JFrame();
        txtCongMaGiaoVien = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtCongTenGiaoVien = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtThang = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtNam = new javax.swing.JTextField();
        btnTinh = new javax.swing.JButton();
        labelCong = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        cbbMaGV = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cbbTenGV = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaGhiChu = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        btnTinhCong = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        btnTimKiem = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        chooserNgaytruc = new com.toedter.calendar.JDateChooser();

        jFrame1.setMinimumSize(new java.awt.Dimension(850, 500));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setText("Mã giáo viên:");

        jLabel13.setText("Tên giáo viên:");

        jLabel14.setText("Ngày trực:");

        jLabel15.setText("Ghi chú:");

        txtAreaGhiChuMoi.setColumns(20);
        txtAreaGhiChuMoi.setRows(5);
        jScrollPane4.setViewportView(txtAreaGhiChuMoi);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Mới");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                        .addGap(4, 4, 4))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(16, 16, 16))
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(29, 29, 29)))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                    .addComponent(txtNgayTrucMoi)
                    .addComponent(cbbMaGVMoi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbbTenGVMoi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(137, 137, 137))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cbbMaGVMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cbbTenGVMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNgayTrucMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(49, 49, 49))
        );

        btnChinhSua.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnChinhSua.setText("Chỉnh sửa");
        btnChinhSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChinhSuaActionPerformed(evt);
            }
        });

        btnHuy.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnHuy.setText("Hủy");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel18.setText("Chỉnh sửa lịch trực");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(242, 242, 242)
                .addComponent(jLabel18)
                .addContainerGap(273, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        cbbMaGVCu.setEnabled(false);

        jLabel8.setText("Mã giáo viên:");

        jLabel9.setText("Tên giáo viên:");

        cbbTenGVCu.setEnabled(false);

        txtNgayTrucCu.setEnabled(false);

        jLabel10.setText("Ngày trực:");

        jLabel11.setText("Ghi chú:");

        txtAreaGhiChuCu.setColumns(20);
        txtAreaGhiChuCu.setRows(5);
        txtAreaGhiChuCu.setEnabled(false);
        jScrollPane3.setViewportView(txtAreaGhiChuCu);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel16.setText("Cũ");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(4, 4, 4))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(16, 16, 16))
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(29, 29, 29)))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(txtNgayTrucCu)
                    .addComponent(cbbMaGVCu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbbTenGVCu, 0, 188, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(133, 133, 133))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addGap(15, 15, 15)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbbMaGVCu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cbbTenGVCu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtNgayTrucCu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jFrame1Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jFrame1Layout.createSequentialGroup()
                                .addGap(143, 143, 143)
                                .addComponent(btnChinhSua)))
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jFrame1Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jFrame1Layout.createSequentialGroup()
                                .addGap(126, 126, 126)
                                .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(26, 26, 26))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnChinhSua, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jFrame2.setMinimumSize(new java.awt.Dimension(500, 450));

        txtCongMaGiaoVien.setText("mã giáo viên");
        txtCongMaGiaoVien.setEnabled(false);

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setText("Mã giáo viên:");

        txtCongTenGiaoVien.setText("tên giáo viên");
        txtCongTenGiaoVien.setEnabled(false);

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setText("Tên giáo viên:");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setText("Tháng:");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setText("Năm:");

        btnTinh.setText("Tính");
        btnTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTinhActionPerformed(evt);
            }
        });

        labelCong.setBackground(new java.awt.Color(255, 255, 255));
        labelCong.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel19.setText("Tính công");

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addGap(236, 236, 236))
            .addGroup(jFrame2Layout.createSequentialGroup()
                .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame2Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jFrame2Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(18, 18, 18)
                                .addComponent(txtThang, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(74, 74, 74)
                                .addComponent(jLabel21)
                                .addGap(61, 61, 61)
                                .addComponent(txtNam, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jFrame2Layout.createSequentialGroup()
                                .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel23))
                                .addGap(82, 82, 82)
                                .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtCongMaGiaoVien, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtCongTenGiaoVien, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jFrame2Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(labelCong, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(193, Short.MAX_VALUE))
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel19)
                .addGap(44, 44, 44)
                .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCongMaGiaoVien, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(36, 36, 36)
                .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCongTenGiaoVien, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(txtNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(labelCong, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 32)); // NOI18N
        jLabel1.setText("Quản lý lịch trực và tính công");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Tên giáo viên", "Ngày trực", "Ghi chú"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jLabel2.setText("Mã giáo viên:");

        jLabel7.setText("Tên giáo viên:");

        jLabel3.setText("Ngày trực:");

        jLabel4.setText("Ghi chú:");

        txtAreaGhiChu.setColumns(20);
        txtAreaGhiChu.setRows(5);
        jScrollPane1.setViewportView(txtAreaGhiChu);

        jLabel6.setText("Công:");

        btnTinhCong.setText("Tính công");
        btnTinhCong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTinhCongActionPerformed(evt);
            }
        });

        btnLamMoi.setText("Refresh");
        btnLamMoi.setToolTipText("");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoibtnLamMoi(evt);
            }
        });

        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        btnThem.setText("Thêm mới lịch trực");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa lịch trực");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa lịch trực");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        jButton1.setText("Quay lại");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTinhCong, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(chooserNgaytruc, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addGap(22, 22, 22))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addGap(18, 18, 18)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cbbTenGV, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cbbMaGV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSua, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnThem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 105, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(112, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(263, 263, 263)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chooserNgaytruc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(cbbMaGV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(29, 29, 29)
                                    .addComponent(cbbTenGV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(29, 29, 29)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addGap(10, 10, 10))
                                        .addComponent(btnLamMoi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 280, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnTinhCong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(41, 41, 41)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        int row = jTable1.getSelectedRow();
        cbbMaGV.setSelectedItem(jTable1.getValueAt(row, 0));
        try {
            chooserNgaytruc.setDate(dateFormat.parse((String)jTable1.getValueAt(row, 2)));
        } catch (ParseException ex) {
            Logger.getLogger(QuanLyLichTrucVaTinhCong.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtAreaGhiChu.setText((String) jTable1.getValueAt(row, 3));
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnLamMoibtnLamMoi(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoibtnLamMoi
        hienThi(lichTrucService.getAll());
        cbbMaGV.setSelectedItem("");

        txtAreaGhiChu.setText("");
    }//GEN-LAST:event_btnLamMoibtnLamMoi

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        GiaoVien giaoVien = null;
        String ngayTruc = null;
        if (!((String) cbbMaGV.getSelectedItem()).equals("")) {
            giaoVien = new GiaoVien();
            giaoVien.setMaGiaoVien((String) cbbMaGV.getSelectedItem());
        }
        if (chooserNgaytruc.getDate()!=null) {
            ngayTruc = dateFormat.format(chooserNgaytruc.getDate());
        }

        hienThi(lichTrucService.find(giaoVien, ngayTruc));
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        LichTruc lichTruc = new LichTruc();
        lichTruc.setGiaoVien(new GiaoVien((String) cbbMaGV.getSelectedItem(), "", "", 0));
        lichTruc.setNgayTruc(dateFormat.format(chooserNgaytruc.getDate()));
        lichTruc.setGhiChu(txtAreaGhiChu.getText());
        int kq = lichTrucService.insert(lichTruc);
        if (kq == 0) {
            JOptionPane.showMessageDialog(this, "Thêm mới lịch trực thất bại!\n"
                + "Vui lòng xem lại dữ liệu nhập vào!");
        } else {
            JOptionPane.showMessageDialog(this, "Thêm mới thành công!");
        }
        hienThi(lichTrucService.getAll());
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        int choose= JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn chỉnh sửa?!\n"
            + "Bản ghi cũ sẽ bị xóa và thay bằng bản ghi mới");
        if(choose==JOptionPane.OK_OPTION){
            LichTruc lichTruc= new LichTruc();
            lichTruc.setGiaoVien(new GiaoVien((String) cbbMaGV.getSelectedItem(), "", "", 0));
            //lichTruc.setNgayTruc(txtNgayTruc.getText());
            //int ktraXoa=lichTrucService.delete(lichTruc);
            lichTruc.setGiaoVien(new GiaoVien((String) cbbMaGV.getSelectedItem(), "", "", 0));
            lichTruc.setNgayTruc(dateFormat.format(chooserNgaytruc.getDate()));
            lichTruc.setGhiChu(txtAreaGhiChu.getText());
            if(lichTrucService.update(lichTruc)==0){
                JOptionPane.showMessageDialog(this, "Sua thanh cong","thanh cong", JOptionPane.ERROR_MESSAGE);
            }else {
            JOptionPane.showMessageDialog(this, "K thanh cong","Lỗi", JOptionPane.ERROR_MESSAGE);
        };
        }
        btnLamMoibtnLamMoi(evt);
            

//            jFrame1.setVisible(false);
//            this.setVisible(true);

//        cbbMaGVCu.setSelectedItem(cbbMaGV.getSelectedItem());
//        txtNgayTrucCu.setText(txtNgayTruc.getText());
//        txtAreaGhiChuCu.setText(txtAreaGhiChu.getText());
//
//        cbbMaGVMoi.setSelectedItem(cbbMaGV.getSelectedItem());
//        txtNgayTrucMoi.setText(txtNgayTruc.getText());
//        txtAreaGhiChuMoi.setText(txtAreaGhiChu.getText());

//        this.setVisible(false);
//        jFrame1.setVisible(true);
//        LichTruc lichTruc=new LichTruc();
//        lichTruc.setGiaoVien(new GiaoVien((String) cbbMaGV.getSelectedItem(), "", "", 0));
//        lichTruc.setNgayTruc(txtNgayTruc.getText());
//        lichTruc.setGhiChu(txtAreaGhiChu.getText());
//        if(lichTrucService.update(lichTruc)==0){
//            JOptionPane.showMessageDialog(this, "Them thanh cong","thanh cong", JOptionPane.ERROR_MESSAGE);
//        }else  if(lichTrucService.update(lichTruc)==1)
//            JOptionPane.showMessageDialog(this, "K thanh cong","Lỗi", JOptionPane.ERROR_MESSAGE);
//        hienThi(lichTrucService.getAll());
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        LichTruc lichTruc = new LichTruc();
        lichTruc.setGiaoVien(new GiaoVien((String) cbbMaGV.getSelectedItem(), "", "", 0));
        lichTruc.setNgayTruc(dateFormat.format(chooserNgaytruc.getDate()));
        lichTruc.setGhiChu(txtAreaGhiChu.getText());

        int choose = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa?\n Mọi thay đổi sẽ không thể hoàn tác!?");
        if (choose == JOptionPane.OK_OPTION) {
            int kq = lichTrucService.delete(lichTruc);
            if (kq == 0) {
                JOptionPane.showMessageDialog(this, "Xóa lịch trực thất bại!\n"
                    + "Vui lòng xem lại dữ liệu nhập vào!");
            } else {
                JOptionPane.showMessageDialog(this, "Xóa lịch trực thành công!");
            }
            hienThi(lichTrucService.getAll());

        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new trangchu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnTinhCongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTinhCongActionPerformed
        // TODO add your handling code here:
        if (((String) cbbMaGV.getSelectedItem()).equals("")) {
            JOptionPane.showMessageDialog(this, "Không thể tính công nếu mã giáo viên trống!");
        } else {
            this.setVisible(false);
            jFrame2.setVisible(true);
            txtCongMaGiaoVien.setText((String) cbbMaGV.getSelectedItem());
            txtCongTenGiaoVien.setText((String) cbbTenGV.getSelectedItem());
            //labelCong.setText("Công=?");
            Calendar calendar= Calendar.getInstance();
            txtThang.setText(String.valueOf(calendar.get(Calendar.MONTH)+1));
            txtNam.setText(String.valueOf(calendar.get(Calendar.YEAR)));
        }
    }//GEN-LAST:event_btnTinhCongActionPerformed

    private void btnTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTinhActionPerformed

        String thang = txtThang.getText();
        String nam = txtNam.getText();
        try {
            int t = Integer.valueOf(thang);
            int n = Integer.valueOf(nam);
            int cong = lichTrucService.count(txtCongMaGiaoVien.getText(), thang, nam);
            labelCong.setText("Công tháng " + thang + " là: " + cong + " (công)");

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Tháng và năm nhập vào không được để trống và phải là 1 số!");
        }
    }//GEN-LAST:event_btnTinhActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        jFrame1.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_btnHuyActionPerformed

    private void btnChinhSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChinhSuaActionPerformed
//        int choose= JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn chỉnh sửa?!\n"
//            + "Bản ghi cũ sẽ bị xóa và thay bằng bản ghi mới");
//        if(choose==JOptionPane.OK_OPTION){
//            LichTruc lichTruc= new LichTruc();
//            lichTruc.setGiaoVien(new GiaoVien((String) cbbMaGVCu.getSelectedItem(), "", "", 0));
//            lichTruc.setNgayTruc(txtNgayTrucCu.getText());
//            int ktraXoa=lichTrucService.delete(lichTruc);
//            lichTruc.setGiaoVien(new GiaoVien((String) cbbMaGVMoi.getSelectedItem(), "", "", 0));
//            lichTruc.setNgayTruc(txtNgayTrucMoi.getText());
//            lichTruc.setGhiChu(txtAreaGhiChuMoi.getText());
//            int ktraThem=lichTrucService.insert(lichTruc);
//
//            if (ktraXoa == 0 && ktraThem == 0) {
//                JOptionPane.showMessageDialog(this, "Cập nhật thất bại");
//            } else if (ktraXoa != 0 && ktraThem == 0) {
//                JOptionPane.showMessageDialog(this, "Đã xóa bản ghi cũ nhưng bản ghi mới thêm vào đã tồn tại hoặc sai sót!\n"
//                    + "Vui lòng quay lại và thêm mới lịch trực phù hợp!");
//
//            } else if (ktraXoa == 0 && ktraThem != 0) {
//                JOptionPane.showMessageDialog(this, "Xóa bản ghi cũ không thành công vì có thể nó đang được sử dụng!\n"
//                    + "Bản ghi mới cập nhật sẽ được thêm mới vào lịch trực kí!");
//            } else if (ktraXoa != 0 && ktraThem != 0) {
//                JOptionPane.showMessageDialog(this, "Cập nhật thành công!");
//            }
//
//            jFrame1.setVisible(false);
//            this.setVisible(true);
//            btnLamMoibtnLamMoi(evt);
//        }
    }//GEN-LAST:event_btnChinhSuaActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChinhSua;
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnTinh;
    private javax.swing.JButton btnTinhCong;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbbMaGV;
    private javax.swing.JComboBox<String> cbbMaGVCu;
    private javax.swing.JComboBox<String> cbbMaGVMoi;
    private javax.swing.JComboBox<String> cbbTenGV;
    private javax.swing.JComboBox<String> cbbTenGVCu;
    private javax.swing.JComboBox<String> cbbTenGVMoi;
    private com.toedter.calendar.JDateChooser chooserNgaytruc;
    private javax.swing.JButton jButton1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelCong;
    private javax.swing.JTextArea txtAreaGhiChu;
    private javax.swing.JTextArea txtAreaGhiChuCu;
    private javax.swing.JTextArea txtAreaGhiChuMoi;
    private javax.swing.JTextField txtCongMaGiaoVien;
    private javax.swing.JTextField txtCongTenGiaoVien;
    private javax.swing.JTextField txtNam;
    private javax.swing.JTextField txtNgayTrucCu;
    private javax.swing.JTextField txtNgayTrucMoi;
    private javax.swing.JTextField txtThang;
    // End of variables declaration//GEN-END:variables
}
